[package]
name = "snake-game"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl2 = { version = "0.38", features = ["ttf"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "1.0"
rand = "0.10"
once_cell = "1.20"
